# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  database: cruncher_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: cruncher_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cruncher_database_production
  pool: 5
  timeout: 5000
